<?php

use Illuminate\Database\Seeder;

class LandingContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            //HOMPAGE MEN WOMEN SEEDER
            [
                "name" => "homepage_banner_men",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Home Page",
                "label" => "Homepage Banner Men",
            ],
            [
                "name" => "homepage_text_men",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Home Page",
                "label" => "Homepage Text Men",
            ],
            [
                "name" => "homepage_url_men",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Home Page",
                "label" => "Homepage URL Men",
            ],

            [
                "name" => "homepage_banner_women",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Home Page",
                "label" => "Homepage Banner Women",
            ],
            [
                "name" => "homepage_text_women",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Home Page",
                "label" => "Homepage Text Women",
            ],
            [
                "name" => "homepage_url_women",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Home Page",
                "label" => "Homepage URL Women",
            ],

            //WOMEN SEEDER
            [
                "name" => "women_main_banner",
                "helper" => 'Height: 600px, Width: 2000px',
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Main Banner",
            ],
            [
                "name" => "women_main_title",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Main Title",
            ],
            [
                "name" => "women_main_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Main URL",
            ],
            [
                "name" => "women_banner_1",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Banner 1",
            ],
            [
                "name" => "women_text_1_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 1 1",
            ],
            [
                "name" => "women_text_1_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 1 2",
            ],
            [
                "name" => "women_url_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women URL 1",
            ],
            [
                "name" => "women_banner_2",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Banner 2",
            ],
            [
                "name" => "women_text_2_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 2 1",
            ],
            [
                "name" => "women_text_2_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 2 2",
            ],
            [
                "name" => "women_url_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women URL 2",
            ],
            [
                "name" => "women_banner_3",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Banner 3",
            ],
            [
                "name" => "women_text_3_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 3 1",
            ],
            [
                "name" => "women_text_3_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 3 2",
            ],
            [
                "name" => "women_url_3",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women URL 3",
            ],
            [
                "name" => "women_banner_4",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Banner 4",
            ],
            [
                "name" => "women_text_4_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 4 1",
            ],
            [
                "name" => "women_text_4_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 4 2",
            ],
            [
                "name" => "women_url_4",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women URL 4",
            ],
            [
                "name" => "women_banner_5",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Banner 5",
            ],
            [
                "name" => "women_text_5_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 5 1",
            ],
            [
                "name" => "women_text_5_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women Text 5 2",
            ],
            [
                "name" => "women_url_5",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Page",
                "label" => "Women URL 5",
            ],
            // MEN SEEDER
            [
                "name" => "men_main_banner",
                "helper" => 'Height: 600px, Width: 2000px',
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Main Banner",
            ],
            [
                "name" => "men_main_title",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Main Title",
            ],
            [
                "name" => "men_main_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Main URL",
            ],
            [
                "name" => "men_banner_1",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Banner 1",
            ],
            [
                "name" => "men_text_1_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 1 1",
            ],
            [
                "name" => "men_text_1_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 1 2",
            ],
            [
                "name" => "men_url_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men URL 1",
            ],
            [
                "name" => "men_banner_2",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Banner 2",
            ],
            [
                "name" => "men_text_2_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 2 1",
            ],
            [
                "name" => "men_text_2_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 2 2",
            ],
            [
                "name" => "men_url_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men URL 2",
            ],
            [
                "name" => "men_banner_3",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Banner 3",
            ],
            [
                "name" => "men_text_3_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 3 1",
            ],
            [
                "name" => "men_text_3_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 3 2",
            ],
            [
                "name" => "men_url_3",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men URL 3",
            ],
            [
                "name" => "men_banner_4",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Banner 4",
            ],
            [
                "name" => "men_text_4_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 4 1",
            ],
            [
                "name" => "men_text_4_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 4 2",
            ],
            [
                "name" => "men_url_4",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men URL 4",
            ],
            [
                "name" => "men_banner_5",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Banner 5",
            ],
            [
                "name" => "men_text_5_1",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 5 1",
            ],
            [
                "name" => "men_text_5_2",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men Text 5 2",
            ],
            [
                "name" => "men_url_5",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Page",
                "label" => "Men URL 5",
            ],

        ];

        foreach($data as $k=>$d) {
            if(DB::table('cms_settings')->where('name',$d['name'])->count()) {
                unset($data[$k]);
            }
        }

        DB::table('cms_settings')->insert($data);
    }
}
