<?php

use Illuminate\Database\Seeder;

class NavContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "name" => "designer_of_the_week",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Designer Navigation",
                "label" => "Designer - Designer of The Week Image",
            ],
            [
                "name" => "designer_designer_of_the_week_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Designer Navigation",
                "label" => "Designer - Designer of The Week URL",
            ],
            [
                "name" => "designer_designer_of_the_week_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Designer Navigation",
                "label" => "Designer - Designer of The Week Text",
            ],
            [
                "name" => "women_blog_image",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Blog Image",
            ],
            [
                "name" => "women_blog_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Blog URL",
            ],
            [
                "name" => "women_designer_1_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 1 Text",
            ],
            [
                "name" => "women_designer_1_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 1 URL",
            ],
            [
                "name" => "women_designer_2_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 2 Text",
            ],
            [
                "name" => "women_designer_2_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 2 URL",
            ],
            [
                "name" => "women_designer_3_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 3 Text",
            ],
            [
                "name" => "women_designer_3_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 3 URL",
            ],
            [
                "name" => "women_designer_4_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 4 Text",
            ],
            [
                "name" => "women_designer_4_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 4 URL",
            ],
            [
                "name" => "women_designer_5_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 5 Text",
            ],
            [
                "name" => "women_designer_5_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Women Navigation",
                "label" => "Women - Designer 5 URL",
            ],
            [
                "name" => "men_blog_image",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Blog Image",
            ],
            [
                "name" => "Men_blog_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Blog URL",
            ],
            [
                "name" => "men_designer_1_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 1 Text",
            ],
            [
                "name" => "men_designer_1_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 1 URL",
            ],
            [
                "name" => "men_designer_2_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 2 Text",
            ],
            [
                "name" => "men_designer_2_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 2 URL",
            ],
            [
                "name" => "men_designer_3_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 3 Text",
            ],
            [
                "name" => "men_designer_3_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 3 URL",
            ],
            [
                "name" => "men_designer_4_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 4 Text",
            ],
            [
                "name" => "men_designer_4_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 4 URL",
            ],
            [
                "name" => "men_designer_5_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 5 Text",
            ],
            [
                "name" => "men_designer_5_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Men Navigation",
                "label" => "Men - Designer 5 URL",
            ],
            [
                "name" => "kid_blog_image",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Blog Image",
            ],
            [
                "name" => "kid_blog_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Blog URL",
            ],
            [
                "name" => "kid_designer_1_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 1 Text",
            ],
            [
                "name" => "kid_designer_1_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 1 URL",
            ],
            [
                "name" => "kid_designer_2_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 2 Text",
            ],
            [
                "name" => "kid_designer_2_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 2 URL",
            ],
            [
                "name" => "kid_designer_3_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 3 Text",
            ],
            [
                "name" => "kid_designer_3_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 3 URL",
            ],
            [
                "name" => "kid_designer_4_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 4 Text",
            ],
            [
                "name" => "kid_designer_4_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 4 URL",
            ],
            [
                "name" => "kid_designer_5_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 5 Text",
            ],
            [
                "name" => "kid_designer_5_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Kids Navigation",
                "label" => "Kid - Designer 5 URL",
            ],
            [
                "name" => "sale_image",
                "content_input_type" => "upload_image",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Sale Navigation",
                "label" => "Sale - Image",
            ],
            [
                "name" => "sale_url",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Sale Navigation",
                "label" => "Sale - URL",
            ],
            [
                "name" => "sale_text",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Sale Navigation",
                "label" => "Sale - Text",
            ],
            [
                "name" => "meta_description",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Meta Tag",
                "label" => "Meta Description",
            ],
            [
                "name" => "meta_keyword",
                "content_input_type" => "text",
                "dataenum" => null,
                "helper" => null,
                "created_at" => date('Y-m-d H:i:s'),
                "group_setting" => "Meta Tag",
                "label" => "Meta Keyword",
            ]
        ];

        foreach($data as $k=>$d) {
            if(DB::table('cms_settings')->where('name',$d['name'])->count()) {
                unset($data[$k]);
            }
        }

        DB::table('cms_settings')->insert($data);
    }
}
