<?php

use Illuminate\Database\Seeder;

class SeederCountries extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $countries = DB::table('countries');

        $countries->truncate();

        $countries_data = [
    		["countries_name" => "Afghanistan", "countries_code" => "AF"],
			["countries_name" => "Aland Islands", "countries_code" => "AX"],
			["countries_name" => "Albania", "countries_code" => "AL"],
			["countries_name" => "Algeria", "countries_code" => "DZ"],
			["countries_name" => "American Samoa", "countries_code" => "AS"],
			["countries_name" => "Andorra", "countries_code" => "AD"],
			["countries_name" => "Angola", "countries_code" => "AO"],
			["countries_name" => "Anguilla", "countries_code" => "AI"],
			["countries_name" => "Antarctica", "countries_code" => "AQ"],
			["countries_name" => "Antigua and Barbuda", "countries_code" => "AG"],
			["countries_name" => "Argentina", "countries_code" => "AR"],
			["countries_name" => "Armenia", "countries_code" => "AM"],
			["countries_name" => "Aruba", "countries_code" => "AW"],
			["countries_name" => "Australia", "countries_code" => "AU"],
			["countries_name" => "Austria", "countries_code" => "AT"],
			["countries_name" => "Azerbaijan", "countries_code" => "AZ"],
			["countries_name" => "Bahamas", "countries_code" => "BS"],
			["countries_name" => "Bahrain", "countries_code" => "BH"],
			["countries_name" => "Bangladesh", "countries_code" => "BD"],
			["countries_name" => "Barbados", "countries_code" => "BB"],
			["countries_name" => "Belarus", "countries_code" => "BY"],
			["countries_name" => "Belgium", "countries_code" => "BE"],
			["countries_name" => "Belize", "countries_code" => "BZ"],
			["countries_name" => "Benin", "countries_code" => "BJ"],
			["countries_name" => "Bermuda", "countries_code" => "BM"],
			["countries_name" => "Bhutan", "countries_code" => "BT"],
			["countries_name" => "Bolivia", "countries_code" => "BO"],
			["countries_name" => "Bosnia and Herzegovina", "countries_code" => "BA"],
			["countries_name" => "Botswana", "countries_code" => "BW"],
			["countries_name" => "Bouvet Island", "countries_code" => "BV"],
			["countries_name" => "Brazil", "countries_code" => "BR"],
			["countries_name" => "British Virgin Islands", "countries_code" => "VG"],
			["countries_name" => "British Indian Ocean Territory", "countries_code" => "IO"],
			["countries_name" => "Brunei Darussalam", "countries_code" => "BN"],
			["countries_name" => "Bulgaria", "countries_code" => "BG"],
			["countries_name" => "Burkina Faso", "countries_code" => "BF"],
			["countries_name" => "Burundi", "countries_code" => "BI"],
			["countries_name" => "Cambodia", "countries_code" => "KH"],
			["countries_name" => "Cameroon", "countries_code" => "CM"],
			["countries_name" => "Canada", "countries_code" => "CA"],
			["countries_name" => "Cape Verde", "countries_code" => "CV"],
			["countries_name" => "Cayman Islands", "countries_code" => "KY"],
			["countries_name" => "Central African Republic", "countries_code" => "CF"],
			["countries_name" => "Chad", "countries_code" => "TD"],
			["countries_name" => "Chile", "countries_code" => "CL"],
			["countries_name" => "China", "countries_code" => "CN"],
			["countries_name" => "Hong Kong, SAR China", "countries_code" => "HK"],
			["countries_name" => "Macao, SAR China", "countries_code" => "MO"],
			["countries_name" => "Christmas Island", "countries_code" => "CX"],
			["countries_name" => "Cocos (Keeling) Islands", "countries_code" => "CC"],
			["countries_name" => "Colombia", "countries_code" => "CO"],
			["countries_name" => "Comoros", "countries_code" => "KM"],
			["countries_name" => "Congo (Brazzaville)", "countries_code" => "CG"],
			["countries_name" => "Congo, (Kinshasa)", "countries_code" => "CD"],
			["countries_name" => "Cook Islands", "countries_code" => "CK"],
			["countries_name" => "Costa Rica", "countries_code" => "CR"],
			["countries_name" => "Côte d'Ivoire", "countries_code" => "CI"],
			["countries_name" => "Croatia", "countries_code" => "HR"],
			["countries_name" => "Cuba", "countries_code" => "CU"],
			["countries_name" => "Cyprus", "countries_code" => "CY"],
			["countries_name" => "Czech Republic", "countries_code" => "CZ"],
			["countries_name" => "Denmark", "countries_code" => "DK"],
			["countries_name" => "Djibouti", "countries_code" => "DJ"],
			["countries_name" => "Dominica", "countries_code" => "DM"],
			["countries_name" => "Dominican Republic", "countries_code" => "DO"],
			["countries_name" => "Ecuador", "countries_code" => "EC"],
			["countries_name" => "Egypt", "countries_code" => "EG"],
			["countries_name" => "El Salvador", "countries_code" => "SV"],
			["countries_name" => "Equatorial Guinea", "countries_code" => "GQ"],
			["countries_name" => "Eritrea", "countries_code" => "ER"],
			["countries_name" => "Estonia", "countries_code" => "EE"],
			["countries_name" => "Ethiopia", "countries_code" => "ET"],
			["countries_name" => "Falkland Islands (Malvinas)", "countries_code" => "FK"],
			["countries_name" => "Faroe Islands", "countries_code" => "FO"],
			["countries_name" => "Fiji", "countries_code" => "FJ"],
			["countries_name" => "Finland", "countries_code" => "FI"],
			["countries_name" => "France", "countries_code" => "FR"],
			["countries_name" => "French Guiana", "countries_code" => "GF"],
			["countries_name" => "French Polynesia", "countries_code" => "PF"],
			["countries_name" => "French Southern Territories", "countries_code" => "TF"],
			["countries_name" => "Gabon", "countries_code" => "GA"],
			["countries_name" => "Gambia", "countries_code" => "GM"],
			["countries_name" => "Georgia", "countries_code" => "GE"],
			["countries_name" => "Germany", "countries_code" => "DE"],
			["countries_name" => "Ghana", "countries_code" => "GH"],
			["countries_name" => "Gibraltar", "countries_code" => "GI"],
			["countries_name" => "Greece", "countries_code" => "GR"],
			["countries_name" => "Greenland", "countries_code" => "GL"],
			["countries_name" => "Grenada", "countries_code" => "GD"],
			["countries_name" => "Guadeloupe", "countries_code" => "GP"],
			["countries_name" => "Guam", "countries_code" => "GU"],
			["countries_name" => "Guatemala", "countries_code" => "GT"],
			["countries_name" => "Guernsey", "countries_code" => "GG"],
			["countries_name" => "Guinea", "countries_code" => "GN"],
			["countries_name" => "Guinea-Bissau", "countries_code" => "GW"],
			["countries_name" => "Guyana", "countries_code" => "GY"],
			["countries_name" => "Haiti", "countries_code" => "HT"],
			["countries_name" => "Heard and Mcdonald Islands", "countries_code" => "HM"],
			["countries_name" => "Holy See (Vatican City State)", "countries_code" => "VA"],
			["countries_name" => "Honduras", "countries_code" => "HN"],
			["countries_name" => "Hungary", "countries_code" => "HU"],
			["countries_name" => "Iceland", "countries_code" => "IS"],
			["countries_name" => "India", "countries_code" => "IN"],
			["countries_name" => "Indonesia", "countries_code" => "ID"],
			["countries_name" => "Iran, Islamic Republic of", "countries_code" => "IR"],
			["countries_name" => "Iraq", "countries_code" => "IQ"],
			["countries_name" => "Ireland", "countries_code" => "IE"],
			["countries_name" => "Isle of Man", "countries_code" => "IM"],
			["countries_name" => "Israel", "countries_code" => "IL"],
			["countries_name" => "Italy", "countries_code" => "IT"],
			["countries_name" => "Jamaica", "countries_code" => "JM"],
			["countries_name" => "Japan", "countries_code" => "JP"],
			["countries_name" => "Jersey", "countries_code" => "JE"],
			["countries_name" => "Jordan", "countries_code" => "JO"],
			["countries_name" => "Kazakhstan", "countries_code" => "KZ"],
			["countries_name" => "Kenya", "countries_code" => "KE"],
			["countries_name" => "Kiribati", "countries_code" => "KI"],
			["countries_name" => "Korea (North)", "countries_code" => "KP"],
			["countries_name" => "Korea (South)", "countries_code" => "KR"],
			["countries_name" => "Kuwait", "countries_code" => "KW"],
			["countries_name" => "Kyrgyzstan", "countries_code" => "KG"],
			["countries_name" => "Lao PDR", "countries_code" => "LA"],
			["countries_name" => "Latvia", "countries_code" => "LV"],
			["countries_name" => "Lebanon", "countries_code" => "LB"],
			["countries_name" => "Lesotho", "countries_code" => "LS"],
			["countries_name" => "Liberia", "countries_code" => "LR"],
			["countries_name" => "Libya", "countries_code" => "LY"],
			["countries_name" => "Liechtenstein", "countries_code" => "LI"],
			["countries_name" => "Lithuania", "countries_code" => "LT"],
			["countries_name" => "Luxembourg", "countries_code" => "LU"],
			["countries_name" => "Macedonia, Republic of", "countries_code" => "MK"],
			["countries_name" => "Madagascar", "countries_code" => "MG"],
			["countries_name" => "Malawi", "countries_code" => "MW"],
			["countries_name" => "Malaysia", "countries_code" => "MY"],
			["countries_name" => "Maldives", "countries_code" => "MV"],
			["countries_name" => "Mali", "countries_code" => "ML"],
			["countries_name" => "Malta", "countries_code" => "MT"],
			["countries_name" => "Marshall Islands", "countries_code" => "MH"],
			["countries_name" => "Martinique", "countries_code" => "MQ"],
			["countries_name" => "Mauritania", "countries_code" => "MR"],
			["countries_name" => "Mauritius", "countries_code" => "MU"],
			["countries_name" => "Mayotte", "countries_code" => "YT"],
			["countries_name" => "Mexico", "countries_code" => "MX"],
			["countries_name" => "Micronesia, Federated States of", "countries_code" => "FM"],
			["countries_name" => "Moldova", "countries_code" => "MD"],
			["countries_name" => "Monaco", "countries_code" => "MC"],
			["countries_name" => "Mongolia", "countries_code" => "MN"],
			["countries_name" => "Montenegro", "countries_code" => "ME"],
			["countries_name" => "Montserrat", "countries_code" => "MS"],
			["countries_name" => "Morocco", "countries_code" => "MA"],
			["countries_name" => "Mozambique", "countries_code" => "MZ"],
			["countries_name" => "Myanmar", "countries_code" => "MM"],
			["countries_name" => "Namibia", "countries_code" => "NA"],
			["countries_name" => "Nauru", "countries_code" => "NR"],
			["countries_name" => "Nepal", "countries_code" => "NP"],
			["countries_name" => "Netherlands", "countries_code" => "NL"],
			["countries_name" => "Netherlands Antilles", "countries_code" => "AN"],
			["countries_name" => "New Caledonia", "countries_code" => "NC"],
			["countries_name" => "New Zealand", "countries_code" => "NZ"],
			["countries_name" => "Nicaragua", "countries_code" => "NI"],
			["countries_name" => "Niger", "countries_code" => "NE"],
			["countries_name" => "Nigeria", "countries_code" => "NG"],
			["countries_name" => "Niue", "countries_code" => "NU"],
			["countries_name" => "Norfolk Island", "countries_code" => "NF"],
			["countries_name" => "Northern Mariana Islands", "countries_code" => "MP"],
			["countries_name" => "Norway", "countries_code" => "NO"],
			["countries_name" => "Oman", "countries_code" => "OM"],
			["countries_name" => "Pakistan", "countries_code" => "PK"],
			["countries_name" => "Palau", "countries_code" => "PW"],
			["countries_name" => "Palestinian Territory", "countries_code" => "PS"],
			["countries_name" => "Panama", "countries_code" => "PA"],
			["countries_name" => "Papua New Guinea", "countries_code" => "PG"],
			["countries_name" => "Paraguay", "countries_code" => "PY"],
			["countries_name" => "Peru", "countries_code" => "PE"],
			["countries_name" => "Philippines", "countries_code" => "PH"],
			["countries_name" => "Pitcairn", "countries_code" => "PN"],
			["countries_name" => "Poland", "countries_code" => "PL"],
			["countries_name" => "Portugal", "countries_code" => "PT"],
			["countries_name" => "Puerto Rico", "countries_code" => "PR"],
			["countries_name" => "Qatar", "countries_code" => "QA"],
			["countries_name" => "Réunion", "countries_code" => "RE"],
			["countries_name" => "Romania", "countries_code" => "RO"],
			["countries_name" => "Russian Federation", "countries_code" => "RU"],
			["countries_name" => "Rwanda", "countries_code" => "RW"],
			["countries_name" => "Saint-Barthélemy", "countries_code" => "BL"],
			["countries_name" => "Saint Helena", "countries_code" => "SH"],
			["countries_name" => "Saint Kitts and Nevis", "countries_code" => "KN"],
			["countries_name" => "Saint Lucia", "countries_code" => "LC"],
			["countries_name" => "Saint-Martin (French part)", "countries_code" => "MF"],
			["countries_name" => "Saint Pierre and Miquelon", "countries_code" => "PM"],
			["countries_name" => "Saint Vincent and Grenadines", "countries_code" => "VC"],
			["countries_name" => "Samoa", "countries_code" => "WS"],
			["countries_name" => "San Marino", "countries_code" => "SM"],
			["countries_name" => "Sao Tome and Principe", "countries_code" => "ST"],
			["countries_name" => "Saudi Arabia", "countries_code" => "SA"],
			["countries_name" => "Senegal", "countries_code" => "SN"],
			["countries_name" => "Serbia", "countries_code" => "RS"],
			["countries_name" => "Seychelles", "countries_code" => "SC"],
			["countries_name" => "Sierra Leone", "countries_code" => "SL"],
			["countries_name" => "Singapore", "countries_code" => "SG"],
			["countries_name" => "Slovakia", "countries_code" => "SK"],
			["countries_name" => "Slovenia", "countries_code" => "SI"],
			["countries_name" => "Solomon Islands", "countries_code" => "SB"],
			["countries_name" => "Somalia", "countries_code" => "SO"],
			["countries_name" => "South Africa", "countries_code" => "ZA"],
			["countries_name" => "South Georgia and the South Sandwich Islands", "countries_code" => "GS"],
			["countries_name" => "South Sudan", "countries_code" => "SS"],
			["countries_name" => "Spain", "countries_code" => "ES"],
			["countries_name" => "Sri Lanka", "countries_code" => "LK"],
			["countries_name" => "Sudan", "countries_code" => "SD"],
			["countries_name" => "Suriname", "countries_code" => "SR"],
			["countries_name" => "Svalbard and Jan Mayen Islands", "countries_code" => "SJ"],
			["countries_name" => "Swaziland", "countries_code" => "SZ"],
			["countries_name" => "Sweden", "countries_code" => "SE"],
			["countries_name" => "Switzerland", "countries_code" => "CH"],
			["countries_name" => "Syrian Arab Republic (Syria)", "countries_code" => "SY"],
			["countries_name" => "Taiwan, Republic of China", "countries_code" => "TW"],
			["countries_name" => "Tajikistan", "countries_code" => "TJ"],
			["countries_name" => "Tanzania, United Republic of", "countries_code" => "TZ"],
			["countries_name" => "Thailand", "countries_code" => "TH"],
			["countries_name" => "Timor-Leste", "countries_code" => "TL"],
			["countries_name" => "Togo", "countries_code" => "TG"],
			["countries_name" => "Tokelau", "countries_code" => "TK"],
			["countries_name" => "Tonga", "countries_code" => "TO"],
			["countries_name" => "Trinidad and Tobago", "countries_code" => "TT"],
			["countries_name" => "Tunisia", "countries_code" => "TN"],
			["countries_name" => "Turkey", "countries_code" => "TR"],
			["countries_name" => "Turkmenistan", "countries_code" => "TM"],
			["countries_name" => "Turks and Caicos Islands", "countries_code" => "TC"],
			["countries_name" => "Tuvalu", "countries_code" => "TV"],
			["countries_name" => "Uganda", "countries_code" => "UG"],
			["countries_name" => "Ukraine", "countries_code" => "UA"],
			["countries_name" => "United Arab Emirates", "countries_code" => "AE"],
			["countries_name" => "United Kingdom", "countries_code" => "GB"],
			["countries_name" => "United States of America", "countries_code" => "US"],
			["countries_name" => "US Minor Outlying Islands", "countries_code" => "UM"],
			["countries_name" => "Uruguay", "countries_code" => "UY"],
			["countries_name" => "Uzbekistan", "countries_code" => "UZ"],
			["countries_name" => "Vanuatu", "countries_code" => "VU"],
			["countries_name" => "Venezuela (Bolivarian Republic)", "countries_code" => "VE"],
			["countries_name" => "Viet Nam", "countries_code" => "VN"],
			["countries_name" => "Virgin Islands, US", "countries_code" => "VI"],
			["countries_name" => "Wallis and Futuna Islands", "countries_code" => "WF"],
			["countries_name" => "Western Sahara", "countries_code" => "EH"],
			["countries_name" => "Yemen", "countries_code" => "YE"],
			["countries_name" => "Zambia", "countries_code" => "ZM"],
			["countries_name" => "Zimbabwe", "countries_code" => "ZW"],
    	];

        $countries->insert($countries_data);
    }
}
